-- =====================================================================
-- MolcaDx pipeline DDL — TimescaleDB (PostgreSQL 15+)
-- schema silver : master data (FigJam ERD 2026-10-01, 55 tables; kpi_result skipped) + facts (Flink)
-- gold DDL      : ../04_gold/ddl_gold.sql
-- =====================================================================
CREATE EXTENSION IF NOT EXISTS timescaledb;
CREATE SCHEMA IF NOT EXISTS silver;

-- ---------------------------------------------------------------------
-- MASTER DATA (generated from Documents/erd/erd_spec_2026-10-01.json)
-- Types: id→bigint · string→text · enum→text (+CHECK when the ERD lists values) · timestamp/datetime→timestamptz
--        key-value/list/ref→jsonb · plain FK & valid_from → NOT NULL · surrogate PK where the ERD had none
-- ---------------------------------------------------------------------
-- ===================== FOUNDATION =====================

-- site_class · FND · SIT
CREATE TABLE silver.site_class (
    site_class_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    code text,   -- string
    name text,   -- string
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (site_class_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- area_class · FND · SIT
CREATE TABLE silver.area_class (
    area_class_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    code text,   -- string
    name text,   -- string
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (area_class_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- work_center_class · FND · SIT
CREATE TABLE silver.work_center_class (
    work_center_class_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    code text,   -- string
    name text,   -- string
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (work_center_class_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- work_unit_class · FND · SIT
CREATE TABLE silver.work_unit_class (
    work_unit_class_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    code text,   -- string
    name text,   -- string
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (work_unit_class_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- equipment_flow · FND · SIT
CREATE TABLE silver.equipment_flow (
    equipment_flow_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    work_center_id bigint NOT NULL,   -- id · FK
    from_work_unit_id bigint NOT NULL,   -- id · FK
    to_work_unit_id bigint NOT NULL,   -- id · FK
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (equipment_flow_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- work_unit_flow · FND · SIT
CREATE TABLE silver.work_unit_flow (
    work_unit_flow_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    from_work_unit_id bigint NOT NULL,   -- id · FK
    to_work_unit_id bigint NOT NULL,   -- id · FK
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (work_unit_flow_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- tenant · FND · SIT
CREATE TABLE silver.tenant (
    tenant_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    tenant_code text,   -- string
    tenant_name text,   -- string
    keycloak_org_id text,   -- string
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (tenant_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- enterprise · FND · SIT
CREATE TABLE silver.enterprise (
    enterprise_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    tenant_id bigint NOT NULL,   -- id · FK
    enterprise_code text,   -- string
    enterprise_name text,   -- string
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (enterprise_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- site · FND · SIT
CREATE TABLE silver.site (
    site_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    enterprise_id bigint NOT NULL,   -- id · FK
    site_code text,   -- string
    site_name text,   -- string
    timezone text,   -- string
    site_class_id bigint,   -- id · FK, nullable
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (site_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- area · FND · SIT
CREATE TABLE silver.area (
    area_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    site_id bigint NOT NULL,   -- id · FK
    area_code text,   -- string
    area_name text,   -- string
    area_class_id bigint,   -- id · FK, nullable
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (area_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- work_center · FND · SIT
CREATE TABLE silver.work_center (
    work_center_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    area_id bigint NOT NULL,   -- id · FK
    work_center_code text,   -- string
    work_center_name text,   -- string
    type text,   -- enum
    work_center_class_id bigint,   -- id · FK, nullable
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (work_center_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- work_unit · FND · SIT
CREATE TABLE silver.work_unit (
    work_unit_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    work_center_id bigint NOT NULL,   -- id · FK
    work_unit_code text,   -- string
    work_unit_name text,   -- string
    work_unit_class_id bigint,   -- id · FK, nullable
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (work_unit_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- fiscal_year · FND · FYR
CREATE TABLE silver.fiscal_year (
    fiscal_year_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    enterprise_id bigint NOT NULL,   -- id · FK
    fiscal_year_label text,   -- string
    calendar_basis text CHECK (calendar_basis IN ('monthly', 'weekly_iso')),   -- enum · monthly, weekly_iso
    start_month integer,   -- int
    end_month integer,   -- int
    start_date date,   -- date
    end_date date,   -- date
    period_pattern text,   -- enum
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (fiscal_year_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- enterprise_shift · FND · SHF
CREATE TABLE silver.enterprise_shift (
    enterprise_shift_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    enterprise_id bigint NOT NULL,   -- id · FK
    shift_label text,   -- string
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (enterprise_shift_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- site_shift · FND · SHF
CREATE TABLE silver.site_shift (
    site_shift_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    site_id bigint NOT NULL,   -- id · FK
    enterprise_shift_id bigint NOT NULL,   -- id · FK
    start_time time,   -- time
    end_time time,   -- time
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (site_shift_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- shift_instance · FND · SHF (gen. by PROD)
CREATE TABLE silver.shift_instance (
    shift_instance_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    site_shift_id bigint NOT NULL,   -- id · FK
    business_date date,   -- date
    start_datetime timestamptz,   -- datetime
    end_datetime timestamptz,   -- datetime
    status text,   -- enum
    PRIMARY KEY (shift_instance_id)
);

-- data_source · FND · DSR
CREATE TABLE silver.data_source (
    data_source_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    site_id bigint NOT NULL,   -- id · FK
    name text,   -- string
    protocol text CHECK (protocol IN ('mqtt', 'opcua')),   -- enum · mqtt, opcua
    node_naming text,   -- enum
    namespace_uri text,   -- string
    topic_root text,   -- string · nullable (MQTT)
    connection_config jsonb,   -- key-value
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (data_source_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- kpi_formula_slot · FND · KPI
CREATE TABLE silver.kpi_formula_slot (
    slot_id text,   -- string · PK
    domain text,   -- enum
    metric text,   -- enum
    iso_element text,   -- string · nullable
    bindable boolean,   -- bool
    PRIMARY KEY (slot_id)
);

-- kpi_parameters · FND · KPI
CREATE TABLE silver.kpi_parameters (
    parameter_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    slot_id text NOT NULL,   -- string · FK
    tag_role text,   -- enum
    transform text,   -- enum
    rank integer,   -- int · nullable
    PRIMARY KEY (parameter_id)
);

-- work_unit_kpi_binding · FND · KPI
CREATE TABLE silver.work_unit_kpi_binding (
    binding_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    work_unit_id bigint NOT NULL,   -- id · FK
    slot_id text NOT NULL,   -- string · FK
    asset_tag_id bigint NOT NULL,   -- id · FK
    transform text,   -- enum
    second_asset_tag_id bigint,   -- id · FK, nullable
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (binding_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- asset_placement · FND · AST
CREATE TABLE silver.asset_placement (
    asset_placement_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- surrogate PK (PRD keys rule)
    asset_id bigint NOT NULL,   -- id · FK
    work_unit_id bigint NOT NULL,   -- id · FK
    placement_role text CHECK (placement_role IN ('primary', 'secondary')),   -- enum · primary, secondary
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (asset_placement_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- asset_class · FND · AST
CREATE TABLE silver.asset_class (
    asset_class_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    code text,   -- string
    name text,   -- string
    parent_class_id bigint,   -- id · FK (self), nullable
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (asset_class_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- asset_type · FND · AST
CREATE TABLE silver.asset_type (
    asset_type_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    asset_class_id bigint NOT NULL,   -- id · FK
    code text,   -- string
    name text,   -- string
    manufacturer text,   -- string
    model text,   -- string
    attributes jsonb,   -- key-value
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (asset_type_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- asset · FND · AST
CREATE TABLE silver.asset (
    asset_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    asset_tag text,   -- string · UQ
    asset_name text,   -- string
    asset_type_id bigint,   -- id · FK, nullable
    serial_number text,   -- string
    parent_asset_id bigint,   -- id · FK (self), nullable
    component_level text,   -- enum
    lifecycle_status text,   -- enum
    commissioning_date date,   -- date
    owner_org_unit_id bigint,   -- id · FK → ? (open)
    attributes jsonb,   -- key-value
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (asset_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- asset_tags · FND · AST
CREATE TABLE silver.asset_tags (
    tag_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    asset_id bigint NOT NULL,   -- id · FK
    data_source_id bigint NOT NULL,   -- id · FK
    work_unit_id bigint,   -- id · FK, conditional
    tag_name text,   -- string
    node text,   -- string
    generated_node text,   -- string · derived
    kind text,   -- enum
    tag_role text,   -- enum · incl. activity_signal, lot_marker
    reject_reason_id bigint,   -- id · FK, nullable
    downtime_reason_id bigint,   -- id · FK, nullable
    uom_id bigint,   -- id · FK, nullable
    count_basis text,   -- enum
    count_side text CHECK (count_side IN ('output', 'input')),   -- enum · conditional — output, input
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (tag_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- asset_product_codes · FND · AST
CREATE TABLE silver.asset_product_codes (
    asset_product_code_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    tag_id bigint NOT NULL,   -- id · FK
    raw_value text,   -- string
    product_id bigint NOT NULL,   -- id · FK
    valid_from timestamptz NOT NULL,   -- timestamptz
    valid_to timestamptz,   -- timestamptz · nullable
    PRIMARY KEY (asset_product_code_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- downtime_reason · FND · REF
CREATE TABLE silver.downtime_reason (
    downtime_reason_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    downtime_category text CHECK (downtime_category IN ('unplanned', 'planned', 'small_stop')),   -- enum · unplanned, planned, small_stop
    code text,   -- string
    name text,   -- string
    PRIMARY KEY (downtime_reason_id)
);

-- downtime_reason_asset · FND · REF
CREATE TABLE silver.downtime_reason_asset (
    downtime_reason_asset_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- surrogate PK (PRD keys rule)
    downtime_reason_id bigint NOT NULL,   -- id · FK
    asset_id bigint NOT NULL,   -- id · FK
    downtime_code text,   -- string
    asset_tag text,   -- string
    PRIMARY KEY (downtime_reason_asset_id)
);

-- reject_reason · FND · REF
CREATE TABLE silver.reject_reason (
    reject_reason_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    code text,   -- string
    name text,   -- string
    PRIMARY KEY (reject_reason_id)
);

-- reject_reason_asset · FND · REF
CREATE TABLE silver.reject_reason_asset (
    reject_reason_asset_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- surrogate PK (PRD keys rule)
    reject_reason_id bigint NOT NULL,   -- id · FK
    asset_id bigint NOT NULL,   -- id · FK
    reject_code text,   -- string
    asset_tag text,   -- string
    PRIMARY KEY (reject_reason_asset_id)
);

-- routing · FND · WMS
CREATE TABLE silver.routing (
    routing_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    product_id bigint NOT NULL,   -- id · FK
    flow_id bigint NOT NULL,   -- id · FK → product_flow
    work_center_id bigint NOT NULL,   -- id · FK
    version integer,   -- int · per flow + work center
    status text CHECK (status IN ('draft', 'released', 'retired')),   -- enum · draft, released, retired
    is_primary boolean,   -- bool · max one per flow + work center
    enforce_sequence boolean,   -- bool · default false
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (routing_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- operation · FND · WMS
CREATE TABLE silver.operation (
    operation_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    routing_id bigint NOT NULL,   -- id · FK
    step_number integer,   -- int
    step_name text,   -- string
    step_type text,   -- string · free text, nullable
    work_unit_id bigint,   -- id · FK, conditional
    required_work_unit_class_id bigint,   -- id · FK, nullable
    cycle_time_value numeric,   -- numeric · discrete/batch
    uom_id bigint,   -- id · FK, nullable — item unit, never time
    time_conversion_id bigint,   -- id · FK, nullable
    batch_size integer,   -- int
    standard_speed_value numeric,   -- numeric · continuous
    speed_uom_id bigint,   -- id · FK, nullable
    standard_setup_time numeric,   -- numeric · nullable
    setup_time_conversion_id bigint,   -- id · FK, conditional
    crew_size integer,   -- int · nullable
    planned_shrinkage numeric,   -- numeric · fraction, nullable
    yield_min_pct numeric,   -- numeric · nullable
    yield_max_pct numeric,   -- numeric · nullable
    max_hold_time numeric,   -- numeric · nullable, > 0
    hold_time_conversion_id bigint,   -- id · FK, conditional
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (operation_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- bom · FND · WMS
CREATE TABLE silver.bom (
    bom_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    product_id bigint NOT NULL,   -- id · FK
    flow_id bigint NOT NULL,   -- id · FK → product_flow
    version integer,   -- int · per flow
    status text CHECK (status IN ('draft', 'released', 'retired')),   -- enum · draft, released, retired
    base_qty numeric,   -- numeric · default 1 — recipe base
    base_uom_id bigint NOT NULL,   -- id · FK
    is_phantom boolean,   -- bool · default false — semi_finished only
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (bom_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- bom_line · FND · WMS
CREATE TABLE silver.bom_line (
    bom_line_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    bom_id bigint NOT NULL,   -- id · FK
    component_product_id bigint NOT NULL,   -- id · FK
    operation_id bigint,   -- id · FK, nullable — empty = first step
    line_use text CHECK (line_use IN ('consumed', 'produced')),   -- enum · consumed, produced
    is_primary_output boolean,   -- bool · conditional — produced only
    qty_per_unit numeric,   -- numeric · per bom.base_qty, net
    uom_id bigint NOT NULL,   -- id · FK
    scrap_factor numeric,   -- numeric · fraction ≥ 0, optional
    dispense_tolerance_type text CHECK (dispense_tolerance_type IN ('percent', 'absolute')),   -- enum · nullable — percent, absolute
    dispense_tolerance_value numeric,   -- numeric · conditional
    PRIMARY KEY (bom_line_id)
);

-- product · FND · PRO
CREATE TABLE silver.product (
    product_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    code text,   -- string
    name text,   -- string
    product_type text CHECK (product_type IN ('raw_material', 'packaging', 'consumable', 'semi_finished', 'finished_good')),   -- enum · raw_material, packaging, consumable, semi_finished, finished_good
    packaging_level text CHECK (packaging_level IN ('primary', 'secondary')),   -- enum · primary, secondary — packaging only
    base_uom_id bigint NOT NULL,   -- id · FK
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (product_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- product_detail · FND · PRO
CREATE TABLE silver.product_detail (
    product_detail_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    product_id bigint NOT NULL UNIQUE,   -- id · FK, UQ (1:1)
    min_weight numeric,   -- numeric
    max_weight numeric,   -- numeric
    standard_weight numeric,   -- numeric
    weight_uom_id bigint NOT NULL,   -- id · FK — mass group only
    length numeric,   -- numeric · nullable
    width numeric,   -- numeric · nullable
    height numeric,   -- numeric · nullable
    barcode text,   -- string
    is_batch_tracked boolean,   -- bool
    shelf_life_days integer,   -- int · nullable
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (product_detail_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- product_uom_conversion · FND · PRO
CREATE TABLE silver.product_uom_conversion (
    product_uom_conversion_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    product_id bigint NOT NULL,   -- id · FK
    from_uom_id bigint NOT NULL,   -- id · FK
    to_uom_id bigint NOT NULL,   -- id · FK
    conversion_value numeric,   -- numeric
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (product_uom_conversion_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- unit_of_measurements · FND · REF
CREATE TABLE silver.unit_of_measurements (
    uom_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    code text,   -- string
    name text,   -- string
    unit text,   -- string
    measurement_group_id bigint NOT NULL,   -- id · FK
    PRIMARY KEY (uom_id)
);

-- measurement_group · FND · REF
CREATE TABLE silver.measurement_group (
    measurement_group_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    code text,   -- string · count, mass, volume, …
    name text,   -- string
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (measurement_group_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- time_conversions · FND · REF
CREATE TABLE silver.time_conversions (
    time_conversions_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    code text,   -- string
    name text,   -- string
    seconds_per_unit numeric,   -- numeric
    PRIMARY KEY (time_conversions_id)
);

-- audit_log · FND · AUD
CREATE TABLE silver.audit_log (
    audit_log_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    occurred_at timestamptz,   -- timestamp · UTC
    domain_code text,   -- string
    module_code text,   -- string
    action text,   -- string
    entity_type text,   -- string · polymorphic
    entity_id bigint NOT NULL,   -- id · no hard FK
    entity_code text,   -- string
    previous_version_entity_id bigint,   -- id
    effective_from date,   -- date
    effective_to date,   -- date
    changes jsonb,   -- list · {field, before, after}
    reason text,   -- string
    source text,   -- enum
    import_batch_id bigint,   -- id
    transaction_id bigint,   -- id
    actor_type text,   -- enum
    actor_subject_id text,   -- string · IDP sub
    actor_display_name text,   -- string
    tenant_id bigint,   -- id
    scope_level text,   -- enum
    PRIMARY KEY (audit_log_id)
);

-- product_flow · FND · WMS
CREATE TABLE silver.product_flow (
    product_flow_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    product_id bigint NOT NULL,   -- id · FK
    flow_code text,   -- string · UQ per product
    flow_name text,   -- string
    is_primary boolean,   -- bool · one per product on any date
    status text CHECK (status IN ('draft', 'released', 'retired')),   -- enum · draft, released, retired
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (product_flow_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- operation_work_unit · FND · WMS
CREATE TABLE silver.operation_work_unit (
    operation_work_unit_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    operation_id bigint NOT NULL,   -- id · FK
    work_unit_id bigint NOT NULL,   -- id · FK
    cycle_time_value numeric,   -- numeric · nullable — station override
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (operation_work_unit_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- operation_dependency · FND · WMS
CREATE TABLE silver.operation_dependency (
    operation_dependency_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    operation_id bigint NOT NULL,   -- id · FK — the step that waits
    predecessor_operation_id bigint NOT NULL,   -- id · FK — same routing, no loops
    PRIMARY KEY (operation_dependency_id)
);

-- operation_parameter · FND · WMS
CREATE TABLE silver.operation_parameter (
    operation_parameter_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    operation_id bigint NOT NULL,   -- id · FK
    parameter_name text,   -- string · UQ per step
    target_value numeric,   -- numeric · nullable
    min_value numeric,   -- numeric · nullable
    max_value numeric,   -- numeric · nullable (≥1 of target/min/max)
    uom_id bigint NOT NULL,   -- id · FK
    is_critical boolean,   -- bool · CPP, default false
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (operation_parameter_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- operation_instruction · FND · WMS
CREATE TABLE silver.operation_instruction (
    operation_instruction_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    operation_id bigint NOT NULL,   -- id · FK
    sequence integer,   -- int · UQ per step
    instruction_text text,   -- string · text, max length TBD
    requires_confirmation boolean,   -- bool · default false
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (operation_instruction_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- operation_check · FND · WMS
CREATE TABLE silver.operation_check (
    operation_check_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    operation_id bigint NOT NULL,   -- id · FK
    sequence integer,   -- int
    check_name text,   -- string · UQ per step
    value_type text CHECK (value_type IN ('numeric', 'pass_fail', 'text')),   -- enum · numeric, pass_fail, text
    target_value numeric,   -- numeric · nullable — numeric only
    min_value numeric,   -- numeric · conditional
    max_value numeric,   -- numeric · conditional
    uom_id bigint,   -- id · FK, conditional — numeric only
    sample_count integer,   -- int · default 1
    frequency_type text CHECK (frequency_type IN ('once', 'start_middle_end', 'interval')),   -- enum · once, start_middle_end, interval
    frequency_interval_value numeric,   -- numeric · conditional — interval
    frequency_interval_conversion_id bigint,   -- id · FK, conditional
    is_critical boolean,   -- bool · default false, not on text
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (operation_check_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- ===================== MAINTENANCE =====================

-- asset_component_link · MNT · AST
CREATE TABLE silver.asset_component_link (
    asset_component_link_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- surrogate PK (PRD keys rule)
    child_asset_id bigint NOT NULL,   -- id · FK
    parent_asset_id bigint NOT NULL,   -- id · FK
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (asset_component_link_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- pm_procedure · MNT · WMS
CREATE TABLE silver.pm_procedure (
    pm_procedure_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    asset_type_id bigint NOT NULL,   -- id · FK
    procedure_code text,   -- string
    procedure_name text,   -- string
    interval_basis text,   -- enum
    interval_value integer,   -- int
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (pm_procedure_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- pm_procedure_step · MNT · WMS
CREATE TABLE silver.pm_procedure_step (
    pm_step_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    pm_procedure_id bigint NOT NULL,   -- id · FK
    step_number integer,   -- int
    description text,   -- string
    estimated_duration numeric,   -- numeric
    valid_from date NOT NULL,   -- date
    valid_to date,   -- date · nullable
    PRIMARY KEY (pm_step_id),
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

-- ===================== PRODUCTION =====================

-- asset_state_log · PROD · MON
CREATE TABLE silver.asset_state_log (
    asset_state_log_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    asset_id bigint NOT NULL,   -- id · FK
    work_unit_id bigint NOT NULL,   -- id · FK — from asset_placement at event time
    shift_instance_id bigint NOT NULL,   -- id · FK
    state text CHECK (state IN ('running', 'idle', 'down', 'setup')),   -- enum · running, idle, down, setup
    downtime_reason_id bigint,   -- id · FK, nullable
    source text CHECK (source IN ('plc', 'manual', 'derived')),   -- enum · plc, manual, derived
    started_at timestamptz,   -- timestamptz
    ended_at timestamptz,   -- timestamptz · nullable
    entered_by text,   -- string · conditional — manual / reason set
    entered_at timestamptz,   -- timestamp · conditional
    PRIMARY KEY (asset_state_log_id)
);

-- work_order_operation_defect · PROD · PLN
CREATE TABLE silver.work_order_operation_defect (
    wo_operation_defect_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    wo_operation_id bigint NOT NULL,   -- id · FK
    defect_code_id bigint NOT NULL,   -- id · FK → reject_reason
    disposition text CHECK (disposition IN ('scrap', 'rework', 'hold')),   -- enum · scrap, rework, hold
    qty numeric,   -- numeric
    uom_id bigint NOT NULL,   -- id · FK
    origin text CHECK (origin IN ('sensor', 'manual_override', 'manual')),   -- enum · sensor, manual_override, manual
    entered_by text,   -- string
    entered_at timestamptz,   -- timestamp
    recorded_at timestamptz,   -- timestamp
    PRIMARY KEY (wo_operation_defect_id)
);

-- work_order_operation_lot · PROD · PLN
CREATE TABLE silver.work_order_operation_lot (
    wo_operation_lot_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    wo_operation_id bigint NOT NULL,   -- id · FK
    direction text CHECK (direction IN ('consumed', 'produced')),   -- enum · consumed, produced
    lot_id text NOT NULL,   -- string · future Inventory FK
    qty numeric,   -- numeric · conditional — produced, on close
    uom_id bigint,   -- id · FK, conditional
    started_at timestamptz,   -- timestamp · conditional
    ended_at timestamptz,   -- timestamp · nullable — empty = open
    closed_by text CHECK (closed_by IN ('lot_marker', 'operator', 'product_change', 'job_end')),   -- enum · lot_marker, operator, product_change, job_end
    entered_by text,   -- string
    entered_at timestamptz,   -- timestamp
    PRIMARY KEY (wo_operation_lot_id)
);

-- work_order_operation · PROD · PLN
CREATE TABLE silver.work_order_operation (
    wo_operation_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    work_order_id bigint NOT NULL,   -- id · FK
    operation_id bigint NOT NULL,   -- id · FK
    work_unit_id bigint NOT NULL,   -- id · FK
    shift_instance_id bigint NOT NULL,   -- id · FK
    good_qty numeric,   -- numeric
    scrap_qty numeric,   -- numeric · derived
    rework_qty numeric,   -- numeric · derived
    actual_start timestamptz,   -- timestamp
    actual_end timestamptz,   -- timestamp
    status text,   -- enum
    PRIMARY KEY (wo_operation_id)
);

-- work_order · PROD · PLN
CREATE TABLE silver.work_order (
    work_order_id bigint GENERATED BY DEFAULT AS IDENTITY,   -- id · PK
    wo_number text,   -- string
    product_id bigint NOT NULL,   -- id · FK
    product_flow_id bigint NOT NULL,   -- id · FK — released flow, default primary
    routing_id bigint NOT NULL,   -- id · FK — one released version (lock)
    bom_id bigint NOT NULL,   -- id · FK — one released version (lock)
    planned_qty numeric,   -- numeric
    uom_id bigint NOT NULL,   -- id · FK
    planned_start timestamptz,   -- timestamp
    planned_end timestamptz,   -- timestamp
    status text,   -- enum
    priority text,   -- enum
    source_system text,   -- string
    PRIMARY KEY (work_order_id)
);

-- ===================== FOREIGN KEYS (102, from the ERD) =====================
ALTER TABLE silver.enterprise ADD FOREIGN KEY (tenant_id) REFERENCES silver.tenant (tenant_id);
ALTER TABLE silver.site ADD FOREIGN KEY (enterprise_id) REFERENCES silver.enterprise (enterprise_id);
ALTER TABLE silver.area ADD FOREIGN KEY (site_id) REFERENCES silver.site (site_id);
ALTER TABLE silver.work_center ADD FOREIGN KEY (area_id) REFERENCES silver.area (area_id);
ALTER TABLE silver.work_unit ADD FOREIGN KEY (work_center_id) REFERENCES silver.work_center (work_center_id);
ALTER TABLE silver.site_shift ADD FOREIGN KEY (enterprise_shift_id) REFERENCES silver.enterprise_shift (enterprise_shift_id);
ALTER TABLE silver.shift_instance ADD FOREIGN KEY (site_shift_id) REFERENCES silver.site_shift (site_shift_id);
ALTER TABLE silver.kpi_parameters ADD FOREIGN KEY (slot_id) REFERENCES silver.kpi_formula_slot (slot_id);
ALTER TABLE silver.work_unit_kpi_binding ADD FOREIGN KEY (slot_id) REFERENCES silver.kpi_formula_slot (slot_id);
ALTER TABLE silver.asset_class ADD FOREIGN KEY (parent_class_id) REFERENCES silver.asset_class (asset_class_id);
ALTER TABLE silver.asset_type ADD FOREIGN KEY (asset_class_id) REFERENCES silver.asset_class (asset_class_id);
ALTER TABLE silver.asset ADD FOREIGN KEY (asset_type_id) REFERENCES silver.asset_type (asset_type_id);
ALTER TABLE silver.asset ADD FOREIGN KEY (parent_asset_id) REFERENCES silver.asset (asset_id);
ALTER TABLE silver.asset_tags ADD FOREIGN KEY (asset_id) REFERENCES silver.asset (asset_id);
ALTER TABLE silver.asset_product_codes ADD FOREIGN KEY (tag_id) REFERENCES silver.asset_tags (tag_id);
ALTER TABLE silver.downtime_reason_asset ADD FOREIGN KEY (downtime_reason_id) REFERENCES silver.downtime_reason (downtime_reason_id);
ALTER TABLE silver.reject_reason_asset ADD FOREIGN KEY (reject_reason_id) REFERENCES silver.reject_reason (reject_reason_id);
ALTER TABLE silver.pm_procedure_step ADD FOREIGN KEY (pm_procedure_id) REFERENCES silver.pm_procedure (pm_procedure_id);
ALTER TABLE silver.work_order ADD FOREIGN KEY (product_flow_id) REFERENCES silver.product_flow (product_flow_id);
ALTER TABLE silver.work_order_operation ADD FOREIGN KEY (operation_id) REFERENCES silver.operation (operation_id);
ALTER TABLE silver.work_order_operation_defect ADD FOREIGN KEY (defect_code_id) REFERENCES silver.reject_reason (reject_reason_id);
ALTER TABLE silver.asset_state_log ADD FOREIGN KEY (asset_id) REFERENCES silver.asset (asset_id);
ALTER TABLE silver.operation ADD FOREIGN KEY (routing_id) REFERENCES silver.routing (routing_id);
ALTER TABLE silver.bom_line ADD FOREIGN KEY (bom_id) REFERENCES silver.bom (bom_id);
ALTER TABLE silver.bom_line ADD FOREIGN KEY (operation_id) REFERENCES silver.operation (operation_id);
ALTER TABLE silver.product ADD FOREIGN KEY (base_uom_id) REFERENCES silver.unit_of_measurements (uom_id);
ALTER TABLE silver.product_detail ADD FOREIGN KEY (product_id) REFERENCES silver.product (product_id);
ALTER TABLE silver.product_detail ADD FOREIGN KEY (weight_uom_id) REFERENCES silver.unit_of_measurements (uom_id);
ALTER TABLE silver.product_uom_conversion ADD FOREIGN KEY (product_id) REFERENCES silver.product (product_id);
ALTER TABLE silver.product_uom_conversion ADD FOREIGN KEY (from_uom_id) REFERENCES silver.unit_of_measurements (uom_id);
ALTER TABLE silver.product_uom_conversion ADD FOREIGN KEY (to_uom_id) REFERENCES silver.unit_of_measurements (uom_id);
ALTER TABLE silver.unit_of_measurements ADD FOREIGN KEY (measurement_group_id) REFERENCES silver.measurement_group (measurement_group_id);
ALTER TABLE silver.site ADD FOREIGN KEY (site_class_id) REFERENCES silver.site_class (site_class_id);
ALTER TABLE silver.area ADD FOREIGN KEY (area_class_id) REFERENCES silver.area_class (area_class_id);
ALTER TABLE silver.work_center ADD FOREIGN KEY (work_center_class_id) REFERENCES silver.work_center_class (work_center_class_id);
ALTER TABLE silver.work_unit ADD FOREIGN KEY (work_unit_class_id) REFERENCES silver.work_unit_class (work_unit_class_id);
ALTER TABLE silver.equipment_flow ADD FOREIGN KEY (work_center_id) REFERENCES silver.work_center (work_center_id);
ALTER TABLE silver.equipment_flow ADD FOREIGN KEY (from_work_unit_id) REFERENCES silver.work_unit (work_unit_id);
ALTER TABLE silver.equipment_flow ADD FOREIGN KEY (to_work_unit_id) REFERENCES silver.work_unit (work_unit_id);
ALTER TABLE silver.work_unit_flow ADD FOREIGN KEY (from_work_unit_id) REFERENCES silver.work_unit (work_unit_id);
ALTER TABLE silver.work_unit_flow ADD FOREIGN KEY (to_work_unit_id) REFERENCES silver.work_unit (work_unit_id);
ALTER TABLE silver.fiscal_year ADD FOREIGN KEY (enterprise_id) REFERENCES silver.enterprise (enterprise_id);
ALTER TABLE silver.enterprise_shift ADD FOREIGN KEY (enterprise_id) REFERENCES silver.enterprise (enterprise_id);
ALTER TABLE silver.site_shift ADD FOREIGN KEY (site_id) REFERENCES silver.site (site_id);
ALTER TABLE silver.data_source ADD FOREIGN KEY (site_id) REFERENCES silver.site (site_id);
ALTER TABLE silver.work_unit_kpi_binding ADD FOREIGN KEY (asset_tag_id) REFERENCES silver.asset_tags (tag_id);
ALTER TABLE silver.work_unit_kpi_binding ADD FOREIGN KEY (second_asset_tag_id) REFERENCES silver.asset_tags (tag_id);
ALTER TABLE silver.asset_placement ADD FOREIGN KEY (asset_id) REFERENCES silver.asset (asset_id);
ALTER TABLE silver.asset_tags ADD FOREIGN KEY (reject_reason_id) REFERENCES silver.reject_reason (reject_reason_id);
ALTER TABLE silver.asset_tags ADD FOREIGN KEY (downtime_reason_id) REFERENCES silver.downtime_reason (downtime_reason_id);
ALTER TABLE silver.downtime_reason_asset ADD FOREIGN KEY (asset_id) REFERENCES silver.asset (asset_id);
ALTER TABLE silver.reject_reason_asset ADD FOREIGN KEY (asset_id) REFERENCES silver.asset (asset_id);
ALTER TABLE silver.asset_component_link ADD FOREIGN KEY (child_asset_id) REFERENCES silver.asset (asset_id);
ALTER TABLE silver.asset_component_link ADD FOREIGN KEY (parent_asset_id) REFERENCES silver.asset (asset_id);
ALTER TABLE silver.pm_procedure ADD FOREIGN KEY (asset_type_id) REFERENCES silver.asset_type (asset_type_id);
ALTER TABLE silver.work_order ADD FOREIGN KEY (product_id) REFERENCES silver.product (product_id);
ALTER TABLE silver.work_order ADD FOREIGN KEY (routing_id) REFERENCES silver.routing (routing_id);
ALTER TABLE silver.work_order ADD FOREIGN KEY (bom_id) REFERENCES silver.bom (bom_id);
ALTER TABLE silver.work_order ADD FOREIGN KEY (uom_id) REFERENCES silver.unit_of_measurements (uom_id);
ALTER TABLE silver.work_order_operation ADD FOREIGN KEY (work_order_id) REFERENCES silver.work_order (work_order_id);
ALTER TABLE silver.work_order_operation_defect ADD FOREIGN KEY (wo_operation_id) REFERENCES silver.work_order_operation (wo_operation_id);
ALTER TABLE silver.work_order_operation_lot ADD FOREIGN KEY (wo_operation_id) REFERENCES silver.work_order_operation (wo_operation_id);
ALTER TABLE silver.asset_state_log ADD FOREIGN KEY (downtime_reason_id) REFERENCES silver.downtime_reason (downtime_reason_id);
ALTER TABLE silver.routing ADD FOREIGN KEY (flow_id) REFERENCES silver.product_flow (product_flow_id);
ALTER TABLE silver.operation_work_unit ADD FOREIGN KEY (operation_id) REFERENCES silver.operation (operation_id);
ALTER TABLE silver.operation_dependency ADD FOREIGN KEY (operation_id) REFERENCES silver.operation (operation_id);
ALTER TABLE silver.operation_dependency ADD FOREIGN KEY (predecessor_operation_id) REFERENCES silver.operation (operation_id);
ALTER TABLE silver.operation_parameter ADD FOREIGN KEY (operation_id) REFERENCES silver.operation (operation_id);
ALTER TABLE silver.operation_parameter ADD FOREIGN KEY (uom_id) REFERENCES silver.unit_of_measurements (uom_id);
ALTER TABLE silver.operation_instruction ADD FOREIGN KEY (operation_id) REFERENCES silver.operation (operation_id);
ALTER TABLE silver.operation_check ADD FOREIGN KEY (operation_id) REFERENCES silver.operation (operation_id);
ALTER TABLE silver.operation_check ADD FOREIGN KEY (uom_id) REFERENCES silver.unit_of_measurements (uom_id);
ALTER TABLE silver.operation_check ADD FOREIGN KEY (frequency_interval_conversion_id) REFERENCES silver.time_conversions (time_conversions_id);
ALTER TABLE silver.bom ADD FOREIGN KEY (flow_id) REFERENCES silver.product_flow (product_flow_id);
ALTER TABLE silver.product_flow ADD FOREIGN KEY (product_id) REFERENCES silver.product (product_id);
ALTER TABLE silver.work_unit_kpi_binding ADD FOREIGN KEY (work_unit_id) REFERENCES silver.work_unit (work_unit_id);
ALTER TABLE silver.asset_placement ADD FOREIGN KEY (work_unit_id) REFERENCES silver.work_unit (work_unit_id);
ALTER TABLE silver.asset_tags ADD FOREIGN KEY (data_source_id) REFERENCES silver.data_source (data_source_id);
ALTER TABLE silver.asset_state_log ADD FOREIGN KEY (shift_instance_id) REFERENCES silver.shift_instance (shift_instance_id);
ALTER TABLE silver.routing ADD FOREIGN KEY (product_id) REFERENCES silver.product (product_id);
ALTER TABLE silver.operation ADD FOREIGN KEY (uom_id) REFERENCES silver.unit_of_measurements (uom_id);
ALTER TABLE silver.operation ADD FOREIGN KEY (time_conversion_id) REFERENCES silver.time_conversions (time_conversions_id);
ALTER TABLE silver.operation ADD FOREIGN KEY (speed_uom_id) REFERENCES silver.unit_of_measurements (uom_id);
ALTER TABLE silver.operation ADD FOREIGN KEY (setup_time_conversion_id) REFERENCES silver.time_conversions (time_conversions_id);
ALTER TABLE silver.operation ADD FOREIGN KEY (hold_time_conversion_id) REFERENCES silver.time_conversions (time_conversions_id);
ALTER TABLE silver.bom ADD FOREIGN KEY (product_id) REFERENCES silver.product (product_id);
ALTER TABLE silver.bom ADD FOREIGN KEY (base_uom_id) REFERENCES silver.unit_of_measurements (uom_id);
ALTER TABLE silver.bom_line ADD FOREIGN KEY (component_product_id) REFERENCES silver.product (product_id);
ALTER TABLE silver.bom_line ADD FOREIGN KEY (uom_id) REFERENCES silver.unit_of_measurements (uom_id);
ALTER TABLE silver.asset_tags ADD FOREIGN KEY (work_unit_id) REFERENCES silver.work_unit (work_unit_id);
ALTER TABLE silver.work_order_operation_defect ADD FOREIGN KEY (uom_id) REFERENCES silver.unit_of_measurements (uom_id);
ALTER TABLE silver.work_order_operation_lot ADD FOREIGN KEY (uom_id) REFERENCES silver.unit_of_measurements (uom_id);
ALTER TABLE silver.asset_state_log ADD FOREIGN KEY (work_unit_id) REFERENCES silver.work_unit (work_unit_id);
ALTER TABLE silver.asset_tags ADD FOREIGN KEY (uom_id) REFERENCES silver.unit_of_measurements (uom_id);
ALTER TABLE silver.asset_product_codes ADD FOREIGN KEY (product_id) REFERENCES silver.product (product_id);
ALTER TABLE silver.work_order_operation ADD FOREIGN KEY (shift_instance_id) REFERENCES silver.shift_instance (shift_instance_id);
ALTER TABLE silver.work_order_operation ADD FOREIGN KEY (work_unit_id) REFERENCES silver.work_unit (work_unit_id);
ALTER TABLE silver.routing ADD FOREIGN KEY (work_center_id) REFERENCES silver.work_center (work_center_id);
ALTER TABLE silver.operation ADD FOREIGN KEY (work_unit_id) REFERENCES silver.work_unit (work_unit_id);
ALTER TABLE silver.operation ADD FOREIGN KEY (required_work_unit_class_id) REFERENCES silver.work_unit_class (work_unit_class_id);
ALTER TABLE silver.operation_work_unit ADD FOREIGN KEY (work_unit_id) REFERENCES silver.work_unit (work_unit_id);

-- FK indexes
CREATE INDEX ON silver.enterprise (tenant_id);
CREATE INDEX ON silver.site (enterprise_id);
CREATE INDEX ON silver.area (site_id);
CREATE INDEX ON silver.work_center (area_id);
CREATE INDEX ON silver.work_unit (work_center_id);
CREATE INDEX ON silver.site_shift (enterprise_shift_id);
CREATE INDEX ON silver.shift_instance (site_shift_id);
CREATE INDEX ON silver.kpi_parameters (slot_id);
CREATE INDEX ON silver.work_unit_kpi_binding (slot_id);
CREATE INDEX ON silver.asset_class (parent_class_id);
CREATE INDEX ON silver.asset_type (asset_class_id);
CREATE INDEX ON silver.asset (asset_type_id);
CREATE INDEX ON silver.asset (parent_asset_id);
CREATE INDEX ON silver.asset_tags (asset_id);
CREATE INDEX ON silver.asset_product_codes (tag_id);
CREATE INDEX ON silver.downtime_reason_asset (downtime_reason_id);
CREATE INDEX ON silver.reject_reason_asset (reject_reason_id);
CREATE INDEX ON silver.pm_procedure_step (pm_procedure_id);
CREATE INDEX ON silver.work_order (product_flow_id);
CREATE INDEX ON silver.work_order_operation (operation_id);
CREATE INDEX ON silver.work_order_operation_defect (defect_code_id);
CREATE INDEX ON silver.asset_state_log (asset_id);
CREATE INDEX ON silver.operation (routing_id);
CREATE INDEX ON silver.bom_line (bom_id);
CREATE INDEX ON silver.bom_line (operation_id);
CREATE INDEX ON silver.product (base_uom_id);
CREATE INDEX ON silver.product_detail (product_id);
CREATE INDEX ON silver.product_detail (weight_uom_id);
CREATE INDEX ON silver.product_uom_conversion (product_id);
CREATE INDEX ON silver.product_uom_conversion (from_uom_id);
CREATE INDEX ON silver.product_uom_conversion (to_uom_id);
CREATE INDEX ON silver.unit_of_measurements (measurement_group_id);
CREATE INDEX ON silver.site (site_class_id);
CREATE INDEX ON silver.area (area_class_id);
CREATE INDEX ON silver.work_center (work_center_class_id);
CREATE INDEX ON silver.work_unit (work_unit_class_id);
CREATE INDEX ON silver.equipment_flow (work_center_id);
CREATE INDEX ON silver.equipment_flow (from_work_unit_id);
CREATE INDEX ON silver.equipment_flow (to_work_unit_id);
CREATE INDEX ON silver.work_unit_flow (from_work_unit_id);
CREATE INDEX ON silver.work_unit_flow (to_work_unit_id);
CREATE INDEX ON silver.fiscal_year (enterprise_id);
CREATE INDEX ON silver.enterprise_shift (enterprise_id);
CREATE INDEX ON silver.site_shift (site_id);
CREATE INDEX ON silver.data_source (site_id);
CREATE INDEX ON silver.work_unit_kpi_binding (asset_tag_id);
CREATE INDEX ON silver.work_unit_kpi_binding (second_asset_tag_id);
CREATE INDEX ON silver.asset_placement (asset_id);
CREATE INDEX ON silver.asset_tags (reject_reason_id);
CREATE INDEX ON silver.asset_tags (downtime_reason_id);
CREATE INDEX ON silver.downtime_reason_asset (asset_id);
CREATE INDEX ON silver.reject_reason_asset (asset_id);
CREATE INDEX ON silver.asset_component_link (child_asset_id);
CREATE INDEX ON silver.asset_component_link (parent_asset_id);
CREATE INDEX ON silver.pm_procedure (asset_type_id);
CREATE INDEX ON silver.work_order (product_id);
CREATE INDEX ON silver.work_order (routing_id);
CREATE INDEX ON silver.work_order (bom_id);
CREATE INDEX ON silver.work_order (uom_id);
CREATE INDEX ON silver.work_order_operation (work_order_id);
CREATE INDEX ON silver.work_order_operation_defect (wo_operation_id);
CREATE INDEX ON silver.work_order_operation_lot (wo_operation_id);
CREATE INDEX ON silver.asset_state_log (downtime_reason_id);
CREATE INDEX ON silver.routing (flow_id);
CREATE INDEX ON silver.operation_work_unit (operation_id);
CREATE INDEX ON silver.operation_dependency (operation_id);
CREATE INDEX ON silver.operation_dependency (predecessor_operation_id);
CREATE INDEX ON silver.operation_parameter (operation_id);
CREATE INDEX ON silver.operation_parameter (uom_id);
CREATE INDEX ON silver.operation_instruction (operation_id);
CREATE INDEX ON silver.operation_check (operation_id);
CREATE INDEX ON silver.operation_check (uom_id);
CREATE INDEX ON silver.operation_check (frequency_interval_conversion_id);
CREATE INDEX ON silver.bom (flow_id);
CREATE INDEX ON silver.product_flow (product_id);
CREATE INDEX ON silver.work_unit_kpi_binding (work_unit_id);
CREATE INDEX ON silver.asset_placement (work_unit_id);
CREATE INDEX ON silver.asset_tags (data_source_id);
CREATE INDEX ON silver.asset_state_log (shift_instance_id);
CREATE INDEX ON silver.routing (product_id);
CREATE INDEX ON silver.operation (uom_id);
CREATE INDEX ON silver.operation (time_conversion_id);
CREATE INDEX ON silver.operation (speed_uom_id);
CREATE INDEX ON silver.operation (setup_time_conversion_id);
CREATE INDEX ON silver.operation (hold_time_conversion_id);
CREATE INDEX ON silver.bom (product_id);
CREATE INDEX ON silver.bom (base_uom_id);
CREATE INDEX ON silver.bom_line (component_product_id);
CREATE INDEX ON silver.bom_line (uom_id);
CREATE INDEX ON silver.asset_tags (work_unit_id);
CREATE INDEX ON silver.work_order_operation_defect (uom_id);
CREATE INDEX ON silver.work_order_operation_lot (uom_id);
CREATE INDEX ON silver.asset_state_log (work_unit_id);
CREATE INDEX ON silver.asset_tags (uom_id);
CREATE INDEX ON silver.asset_product_codes (product_id);
CREATE INDEX ON silver.work_order_operation (shift_instance_id);
CREATE INDEX ON silver.work_order_operation (work_unit_id);
CREATE INDEX ON silver.routing (work_center_id);
CREATE INDEX ON silver.operation (work_unit_id);
CREATE INDEX ON silver.operation (required_work_unit_class_id);
CREATE INDEX ON silver.operation_work_unit (work_unit_id);

-- ---------------------------------------------------------------------
-- SILVER facts (Flink). No FKs on hypertables: Flink resolves ids; keeps inserts fast and retention simple.
-- ---------------------------------------------------------------------
-- Counter deltas, role total / good
CREATE TABLE silver.production_events (
    event_time        timestamptz   NOT NULL,
    tag_id            bigint        NOT NULL,
    asset_id          bigint        NOT NULL,
    asset_code        text,
    work_unit_id      bigint,
    shift_instance_id bigint,
    business_date     date,
    product_id        bigint,
    product_code      text,
    role              text          NOT NULL CHECK (role IN ('total','good')),
    uom_id            bigint,
    raw_value         numeric(18,3) NOT NULL,
    cleaned_value     numeric(18,3) NOT NULL CHECK (cleaned_value >= 0),
    is_reset          boolean       NOT NULL DEFAULT false,
    source_tag        text  NOT NULL,
    raw_payload       text,
    created_at        timestamptz   NOT NULL DEFAULT now(),
    PRIMARY KEY (tag_id, event_time)
);
SELECT create_hypertable('silver.production_events', by_range('event_time', INTERVAL '1 day'));
CREATE INDEX ON silver.production_events (work_unit_id, event_time DESC);
CREATE INDEX ON silver.production_events (shift_instance_id);
ALTER TABLE silver.production_events SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'tag_id',
    timescaledb.compress_orderby   = 'event_time DESC');
SELECT add_compression_policy('silver.production_events', INTERVAL '3 days');
SELECT add_retention_policy  ('silver.production_events', INTERVAL '1 month');

-- Counter deltas, role reject
CREATE TABLE silver.reject_events (
    event_time         timestamptz   NOT NULL,
    tag_id             bigint        NOT NULL,
    asset_id           bigint        NOT NULL,
    asset_code         text,
    work_unit_id       bigint,
    shift_instance_id  bigint,
    business_date      date,
    product_id         bigint,
    product_code       text,
    reject_reason_id   bigint,
    reject_reason_code text,
    uom_id             bigint,
    raw_value          numeric(18,3) NOT NULL,
    cleaned_value      numeric(18,3) NOT NULL CHECK (cleaned_value >= 0),
    is_reset           boolean       NOT NULL DEFAULT false,
    source_tag         text  NOT NULL,
    raw_payload        text,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    PRIMARY KEY (tag_id, event_time)
);
SELECT create_hypertable('silver.reject_events', by_range('event_time', INTERVAL '1 day'));
CREATE INDEX ON silver.reject_events (work_unit_id, event_time DESC);
CREATE INDEX ON silver.reject_events (shift_instance_id);
ALTER TABLE silver.reject_events SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'tag_id',
    timescaledb.compress_orderby   = 'event_time DESC');
SELECT add_compression_policy('silver.reject_events', INTERVAL '3 days');
SELECT add_retention_policy  ('silver.reject_events', INTERVAL '1 month');

-- Stops as the MACHINE saw them (Flink only). One row per stop piece per shift. Kept forever.
-- People never update this table: edits -> silver/gold.downtime_edit, manual stops -> downtime_entry (views apply them).
-- Flink stall rule (fixed in code, no config table): gap < 60 s = nothing (speed loss) · 60–300 s = small_stop · > 300 s = unplanned
CREATE TABLE silver.downtime_events (
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_event_id     text        NOT NULL UNIQUE,  -- deterministic: 'wu{work_unit_id}-t{tag_id}-{start_at epoch ms}' (derived);
                                                      -- MES generates its own for manual rows. Gold: downtime_reports.source_event_id
                                                      -- and downtime_log_events.event_id carry the SAME string. Flink upsert key.
    asset_id            bigint      NOT NULL,
    tag_id              bigint,                       -- watched total tag (derived rows)
    work_unit_id        bigint      NOT NULL,
    shift_instance_id   bigint      NOT NULL,
    business_date       date        NOT NULL,
    category            varchar(20) NOT NULL CHECK (category IN ('planned','unplanned','small_stop')),
    downtime_reason_id  bigint,                       -- primary reason; NULL = unlabelled (counts as unplanned)
    downtime_reason_ids bigint[]    NOT NULL DEFAULT '{}',  -- every reason cited, ordered by when its signal turned on;
                                                      -- element 1 = primary. Gold reason / reasons arrays come from here
    product_id          bigint,                       -- SKU running when the stop STARTED (raw code -> asset_product_codes)
    source              varchar(10) NOT NULL CHECK (source IN ('derived','plc')),   -- machine only; manual stops: downtime_entry
    start_at            timestamptz NOT NULL,
    end_at              timestamptz,                  -- NULL = still stopped
    duration            bigint GENERATED ALWAYS AS
                        ((extract(epoch FROM (end_at - start_at)) * 1000)::bigint) STORED,   -- ms
    stop_group_id       bigint      NOT NULL,         -- same for all pieces of one stop split at shift boundaries
    assumed_start       boolean     NOT NULL DEFAULT false,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CHECK (end_at IS NULL OR end_at >= start_at),
    CHECK (downtime_reason_id IS NOT DISTINCT FROM downtime_reason_ids[1]),
    CHECK (array_position(downtime_reason_ids, NULL) IS NULL)
);
CREATE INDEX ON silver.downtime_events (shift_instance_id, work_unit_id);
CREATE INDEX ON silver.downtime_events (asset_id, start_at DESC);
CREATE INDEX ON silver.downtime_events (start_at) WHERE end_at IS NULL;   -- open stops (live)

-- 1-minute continuous aggregates (kept after raw retention)
CREATE MATERIALIZED VIEW silver.production_events_1m
WITH (timescaledb.continuous, timescaledb.materialized_only = false) AS
SELECT time_bucket(INTERVAL '1 minute', event_time) AS bucket_time,
       tag_id, asset_id, work_unit_id, shift_instance_id, business_date, product_id, uom_id, role,
       sum(cleaned_value) AS qty,
       count(*)           AS event_count,
       count(*) FILTER (WHERE cleaned_value > 0) AS positive_count,   -- readings that added output (reject freq)
       bool_or(is_reset)  AS had_reset
FROM silver.production_events
GROUP BY 1,2,3,4,5,6,7,8,9
WITH NO DATA;
SELECT add_continuous_aggregate_policy('silver.production_events_1m',
       start_offset => INTERVAL '2 hours', end_offset => INTERVAL '1 minute', schedule_interval => INTERVAL '1 minute');
ALTER MATERIALIZED VIEW silver.production_events_1m SET (timescaledb.compress = true);
SELECT add_compression_policy('silver.production_events_1m', compress_after => INTERVAL '7 days');

CREATE MATERIALIZED VIEW silver.reject_events_1m
WITH (timescaledb.continuous, timescaledb.materialized_only = false) AS
SELECT time_bucket(INTERVAL '1 minute', event_time) AS bucket_time,
       tag_id, asset_id, work_unit_id, shift_instance_id, business_date, product_id, uom_id, reject_reason_id,
       sum(cleaned_value) AS qty,
       count(*)           AS event_count,
       count(*) FILTER (WHERE cleaned_value > 0) AS positive_count,   -- readings that added output (reject freq)
       bool_or(is_reset)  AS had_reset
FROM silver.reject_events
GROUP BY 1,2,3,4,5,6,7,8,9
WITH NO DATA;
SELECT add_continuous_aggregate_policy('silver.reject_events_1m',
       start_offset => INTERVAL '2 hours', end_offset => INTERVAL '1 minute', schedule_interval => INTERVAL '1 minute');
ALTER MATERIALIZED VIEW silver.reject_events_1m SET (timescaledb.compress = true);
SELECT add_compression_policy('silver.reject_events_1m', compress_after => INTERVAL '7 days');



-- ---------------------------------------------------------------------
-- FUNCTION: final work unit(s) of each work center on a business date (decided 2026-10-02)
-- equipment_flow is the linked list of machines inside a work center (from_work_unit_id -> to_work_unit_id).
-- A FINAL work unit has no outgoing edge on that date; parallel finals are all returned (summed by the caller).
-- Work-center finished good (good_out) = Σ good of these work units; everything else = Σ of all work units.
-- A work unit with no edge at all counts as final, so a work center without any flow rows = all its work units.
-- ---------------------------------------------------------------------
CREATE FUNCTION silver.fn_work_center_final_work_units(p_business_date date)
RETURNS TABLE (work_center_id bigint, work_unit_id bigint)
LANGUAGE sql STABLE AS $$
  SELECT wu.work_center_id, wu.work_unit_id
  FROM silver.work_unit wu
  WHERE wu.valid_from <= p_business_date
    AND (wu.valid_to IS NULL OR wu.valid_to >= p_business_date)
    AND NOT EXISTS (
      SELECT 1 FROM silver.equipment_flow f
      WHERE f.work_center_id    = wu.work_center_id
        AND f.from_work_unit_id = wu.work_unit_id
        AND f.valid_from <= p_business_date
        AND (f.valid_to IS NULL OR f.valid_to > p_business_date))
$$;
-- ---------------------------------------------------------------------
-- fn_uom_factor: multiply a quantity in p_from by this to get p_to, for one product on one date (PRD PRO-003 / WMS-003).
-- Paths, first that works: same unit · one row forward (×) · one row backward (÷) · two rows via the product's base
-- unit · weight → units via product_detail.standard_weight (PRD KPI-003, shrinkage not applied).
-- NULL = no path ("cannot compute"; never guessed).
-- ---------------------------------------------------------------------
CREATE FUNCTION silver.fn_uom_factor(p_product_id bigint, p_from bigint, p_to bigint, p_date date)
RETURNS numeric LANGUAGE sql STABLE AS $$
  WITH c AS (
    SELECT from_uom_id AS f, to_uom_id AS t, conversion_value AS v
    FROM silver.product_uom_conversion
    WHERE product_id = p_product_id AND valid_from <= p_date AND (valid_to IS NULL OR valid_to > p_date)),
  p AS (SELECT base_uom_id AS b FROM silver.product WHERE product_id = p_product_id),
  w AS (SELECT standard_weight AS sw, weight_uom_id AS wu FROM silver.product_detail
        WHERE product_id = p_product_id AND valid_from <= p_date AND (valid_to IS NULL OR valid_to > p_date)
          AND standard_weight > 0 LIMIT 1),
  to_base AS (   -- factor p_from -> base
    SELECT coalesce(
      CASE WHEN p_from = p.b THEN 1::numeric END,
      (SELECT v FROM c WHERE f = p_from AND t = p.b LIMIT 1),
      (SELECT 1 / v FROM c WHERE f = p.b AND t = p_from LIMIT 1),
      (SELECT 1 / w.sw FROM w WHERE w.wu = p_from)) AS fac
    FROM p),
  from_base AS ( -- factor base -> p_to
    SELECT coalesce(
      CASE WHEN p_to = p.b THEN 1::numeric END,
      (SELECT v FROM c WHERE f = p.b AND t = p_to LIMIT 1),
      (SELECT 1 / v FROM c WHERE f = p_to AND t = p.b LIMIT 1),
      (SELECT w.sw FROM w WHERE w.wu = p_to)) AS fac
    FROM p)
  SELECT CASE
    WHEN p_from IS NULL OR p_to IS NULL OR p_product_id IS NULL THEN NULL
    WHEN p_from = p_to THEN 1::numeric
    ELSE coalesce(
      (SELECT v FROM c WHERE f = p_from AND t = p_to LIMIT 1),
      (SELECT 1 / v FROM c WHERE f = p_to AND t = p_from LIMIT 1),
      (SELECT to_base.fac * from_base.fac FROM to_base, from_base))
  END
$$;

-- ---------------------------------------------------------------------
-- fn_cycle_time: ideal seconds per item of the operation's item unit, for a product on a work unit on a date
-- (PRD WMS-003: station override, else the step; primary released routing of the product at the work unit's
-- work center; a class-based step matches the work unit's class). Discrete/batch only (cycle_time_value).
-- ---------------------------------------------------------------------
CREATE FUNCTION silver.fn_cycle_time(p_work_unit_id bigint, p_product_id bigint, p_date date)
RETURNS TABLE (ct_s numeric, op_uom_id bigint, batch_size integer, operation_id bigint)
LANGUAGE sql STABLE AS $$
  SELECT coalesce(owu.cycle_time_value, o.cycle_time_value) * tc.seconds_per_unit,
         o.uom_id, coalesce(nullif(o.batch_size, 0), 1), o.operation_id
  FROM silver.work_unit wu
  JOIN silver.routing r
    ON r.product_id = p_product_id AND r.work_center_id = wu.work_center_id
   AND r.status = 'released' AND r.is_primary
   AND r.valid_from <= p_date AND (r.valid_to IS NULL OR r.valid_to > p_date)
  JOIN silver.operation o
    ON o.routing_id = r.routing_id
   AND (o.work_unit_id = wu.work_unit_id
        OR (o.work_unit_id IS NULL AND o.required_work_unit_class_id = wu.work_unit_class_id))
   AND o.valid_from <= p_date AND (o.valid_to IS NULL OR o.valid_to > p_date)
  JOIN silver.time_conversions tc ON tc.time_conversions_id = o.time_conversion_id
  LEFT JOIN silver.operation_work_unit owu
    ON owu.operation_id = o.operation_id AND owu.work_unit_id = wu.work_unit_id
   AND owu.valid_from <= p_date AND (owu.valid_to IS NULL OR owu.valid_to > p_date)
  WHERE wu.work_unit_id = p_work_unit_id AND o.cycle_time_value > 0
  ORDER BY o.step_number
  LIMIT 1
$$;

-- =====================================================================
-- EDITING (approved 2026-10-02). Fact rows are never changed; people write APPEND-ONLY edit/entry tables.
--   silver.* = shopfloor: shift open .. 48 h after shift end.   gold.* (ddl_gold.sql) = report: after that.
--   An approved report (gold.report_approval) is frozen: no edits in either domain until it is reopened.
--   The edit row IS the trail (who, when, old -> new, required reason; void instead of delete) and every insert or
--   void also writes one silver.audit_log row (PRD F-14: same transaction, append-only).
--   Views (ddl_views.sql) apply: gold edit > silver edit > machine value; latest non-voided edit per field wins.
-- =====================================================================

-- Clock used by the edit-window rule; tests may pin it with: SET silver.now_override = '2026-09-30 09:00+00';
CREATE FUNCTION silver.fn_now() RETURNS timestamptz LANGUAGE sql STABLE AS $$
  SELECT coalesce(nullif(current_setting('silver.now_override', true), '')::timestamptz, now())
$$;

-- Common trigger: append-only. DELETE refused; UPDATE only to void a live row (voided_at, voided_by, void_reason).
CREATE FUNCTION silver.trg_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION '%.% is append-only: void the row instead of deleting it', TG_TABLE_SCHEMA, TG_TABLE_NAME;
  END IF;
  IF OLD.voided_at IS NOT NULL THEN
    RAISE EXCEPTION '%.%: row is already voided', TG_TABLE_SCHEMA, TG_TABLE_NAME;
  END IF;
  IF NEW.voided_at IS NULL OR NEW.voided_by IS NULL OR coalesce(btrim(NEW.void_reason), '') = '' THEN
    RAISE EXCEPTION '%.%: an update must void the row (voided_at, voided_by, void_reason)', TG_TABLE_SCHEMA, TG_TABLE_NAME;
  END IF;
  IF (to_jsonb(NEW) - ARRAY['voided_at','voided_by','void_reason'])
     IS DISTINCT FROM (to_jsonb(OLD) - ARRAY['voided_at','voided_by','void_reason']) THEN
    RAISE EXCEPTION '%.%: only voided_at, voided_by and void_reason may change', TG_TABLE_SCHEMA, TG_TABLE_NAME;
  END IF;
  RETURN NEW;
END $$;

-- Common trigger: one silver.audit_log row per insert (create) and per void, in the same transaction.
-- TG_ARGV[0] = module_code, TG_ARGV[1] = id column name.
CREATE FUNCTION silver.trg_edit_audit() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE j jsonb := to_jsonb(NEW);
BEGIN
  INSERT INTO silver.audit_log (occurred_at, domain_code, module_code, action, entity_type, entity_id, entity_code,
                                changes, reason, source, transaction_id, actor_type, actor_subject_id, actor_display_name)
  VALUES (now(), 'PROD', TG_ARGV[0],
          CASE WHEN TG_OP = 'INSERT' THEN 'create' ELSE 'void' END,
          TG_TABLE_SCHEMA || '.' || TG_TABLE_NAME,
          (j ->> TG_ARGV[1])::bigint,
          coalesce(j ->> 'source_event_id', j ->> 'kind'),
          CASE WHEN TG_OP = 'INSERT'
               THEN jsonb_strip_nulls(j - ARRAY['reason','created_by','created_by_name','created_at',
                                                'voided_at','voided_by','void_reason'])
               ELSE jsonb_build_object('voided_at', j -> 'voided_at', 'voided_by', j -> 'voided_by') END,
          CASE WHEN TG_OP = 'INSERT' THEN j ->> 'reason' ELSE j ->> 'void_reason' END,
          'app', txid_current(), 'user',
          CASE WHEN TG_OP = 'INSERT' THEN j ->> 'created_by' ELSE j ->> 'voided_by' END,
          CASE WHEN TG_OP = 'INSERT' THEN j ->> 'created_by_name' ELSE NULL END);
  RETURN NULL;
END $$;

-- Edit window: silver = until 48 h after shift end, gold = after that; approved report = frozen everywhere.
CREATE FUNCTION silver.fn_assert_edit_window(p_domain text, p_shift_instance_id bigint, p_work_unit_id bigint)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE v_end timestamptz; v_status text;
BEGIN
  SELECT end_datetime INTO v_end FROM silver.shift_instance WHERE shift_instance_id = p_shift_instance_id;
  IF v_end IS NULL THEN
    RAISE EXCEPTION 'unknown shift_instance_id %', p_shift_instance_id;
  END IF;
  SELECT status INTO v_status FROM gold.report_approval
   WHERE shift_instance_id = p_shift_instance_id AND work_unit_id = p_work_unit_id;
  IF v_status = 'approved' THEN
    RAISE EXCEPTION 'report (work unit %, shift %) is approved: reopen it before editing', p_work_unit_id, p_shift_instance_id;
  END IF;
  IF p_domain = 'silver' AND silver.fn_now() > v_end + interval '48 hours' THEN
    RAISE EXCEPTION 'shift % ended more than 48 h ago: edit it in gold', p_shift_instance_id;
  END IF;
  IF p_domain = 'gold' AND silver.fn_now() <= v_end + interval '48 hours' THEN
    RAISE EXCEPTION 'shift % is still in the shopfloor window (48 h): edit it in silver', p_shift_instance_id;
  END IF;
END $$;

-- ---------------------------------------------------------------------
-- S1-S3: downtime_edit — override ONE field of a stop (category | reasons | detail_reason | actions | maintained_by)
-- old_* is filled by the trigger from the current effective value (the before/after of the trail).
-- ---------------------------------------------------------------------
CREATE TABLE silver.downtime_edit (
    edit_id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_event_id     text        NOT NULL,          -- the stop (downtime_events or downtime_entry)
    work_unit_id        bigint,                         -- filled by the trigger
    shift_instance_id   bigint,                         -- filled by the trigger
    field               varchar(20) NOT NULL CHECK (field IN ('category','reasons','detail_reason','actions','maintained_by')),
    new_category        varchar(20) CHECK (new_category IN ('planned','unplanned','small_stop')),
    new_reason_ids      bigint[],                       -- ordered, element 1 = primary; '{}' = unlabelled
    new_detail_reason   text        CHECK (length(new_detail_reason) <= 2000),
    new_actions         text[],
    new_maintained_by   varchar(255),
    old_category        varchar(20),
    old_reason_ids      bigint[],
    old_detail_reason   text,
    old_actions         text[],
    old_maintained_by   varchar(255),
    reason              text        NOT NULL CHECK (btrim(reason) <> ''),   -- why the edit was made (required)
    created_by          text        NOT NULL,           -- IDP subject
    created_by_name     varchar(255),
    created_at          timestamptz NOT NULL DEFAULT now(),
    voided_at           timestamptz,
    voided_by           text,
    void_reason         text,
    CHECK (field <> 'category' OR new_category IS NOT NULL),
    CHECK (field <> 'reasons'  OR (new_reason_ids IS NOT NULL AND array_position(new_reason_ids, NULL) IS NULL)),
    CHECK (new_actions IS NULL OR array_position(new_actions, NULL) IS NULL)
);
CREATE INDEX ON silver.downtime_edit (source_event_id, field, created_at DESC) WHERE voided_at IS NULL;
CREATE INDEX ON silver.downtime_edit (shift_instance_id, work_unit_id);

CREATE FUNCTION silver.trg_downtime_edit_before() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE r record;
BEGIN
  SELECT * INTO r FROM silver.v_downtime_effective WHERE source_event_id = NEW.source_event_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'unknown stop %', NEW.source_event_id;
  END IF;
  PERFORM silver.fn_assert_edit_window(TG_ARGV[0], r.shift_instance_id, r.work_unit_id);
  NEW.work_unit_id      := r.work_unit_id;
  NEW.shift_instance_id := r.shift_instance_id;
  NEW.old_category      := r.category;
  NEW.old_reason_ids    := r.reason_ids;
  NEW.old_detail_reason := r.detail_reason;
  NEW.old_actions       := r.actions;
  NEW.old_maintained_by := r.maintained_by;
  RETURN NEW;
END $$;

CREATE TRIGGER downtime_edit_before BEFORE INSERT ON silver.downtime_edit
  FOR EACH ROW EXECUTE FUNCTION silver.trg_downtime_edit_before('silver');
CREATE TRIGGER downtime_edit_append_only BEFORE UPDATE OR DELETE ON silver.downtime_edit
  FOR EACH ROW EXECUTE FUNCTION silver.trg_append_only();
CREATE TRIGGER downtime_edit_audit AFTER INSERT OR UPDATE ON silver.downtime_edit
  FOR EACH ROW EXECUTE FUNCTION silver.trg_edit_audit('MON', 'edit_id');

-- ---------------------------------------------------------------------
-- S4: downtime_entry — a manual stop for time no machine row covers (e.g. a break where the counter kept moving)
-- ---------------------------------------------------------------------
CREATE TABLE silver.downtime_entry (
    entry_id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_event_id   text GENERATED ALWAYS AS ('manual-' || entry_id) STORED UNIQUE,
    work_unit_id      bigint      NOT NULL,
    asset_id          bigint      NOT NULL,            -- the work unit's primary asset
    shift_instance_id bigint      NOT NULL,
    business_date     date,                            -- filled by the trigger
    category          varchar(20) NOT NULL CHECK (category IN ('planned','unplanned','small_stop')),
    reason_ids        bigint[]    NOT NULL DEFAULT '{}' CHECK (array_position(reason_ids, NULL) IS NULL),
    detail_reason     text        CHECK (length(detail_reason) <= 2000),
    actions           text[],
    maintained_by     varchar(255),
    product_id        bigint,
    start_at          timestamptz NOT NULL,
    end_at            timestamptz NOT NULL,
    reason            text        NOT NULL CHECK (btrim(reason) <> ''),
    created_by        text        NOT NULL,
    created_by_name   varchar(255),
    created_at        timestamptz NOT NULL DEFAULT now(),
    voided_at         timestamptz,
    voided_by         text,
    void_reason       text,
    CHECK (end_at > start_at)
);
CREATE INDEX ON silver.downtime_entry (shift_instance_id, work_unit_id) WHERE voided_at IS NULL;

CREATE FUNCTION silver.trg_downtime_entry_before() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE s record;
BEGIN
  SELECT * INTO s FROM silver.shift_instance WHERE shift_instance_id = NEW.shift_instance_id;
  IF NEW.start_at < s.start_datetime OR NEW.end_at > s.end_datetime THEN
    RAISE EXCEPTION 'manual stop must lie inside shift % (% .. %)', NEW.shift_instance_id, s.start_datetime, s.end_datetime;
  END IF;
  PERFORM silver.fn_assert_edit_window(TG_ARGV[0], NEW.shift_instance_id, NEW.work_unit_id);
  NEW.business_date := s.business_date;
  RETURN NEW;
END $$;

CREATE TRIGGER downtime_entry_before BEFORE INSERT ON silver.downtime_entry
  FOR EACH ROW EXECUTE FUNCTION silver.trg_downtime_entry_before('silver');
CREATE TRIGGER downtime_entry_append_only BEFORE UPDATE OR DELETE ON silver.downtime_entry
  FOR EACH ROW EXECUTE FUNCTION silver.trg_append_only();
CREATE TRIGGER downtime_entry_audit AFTER INSERT OR UPDATE ON silver.downtime_entry
  FOR EACH ROW EXECUTE FUNCTION silver.trg_edit_audit('MON', 'entry_id');

-- ---------------------------------------------------------------------
-- S5-S7: quality_entry — manual reject / rework ADDED to a work unit × shift, or a reject_override that moves
-- quantity of one sensor reject node to another reason (total reject unchanged). Quantities are converted to the
-- product's base unit when read (fn_uom_factor as of business_date).
-- ---------------------------------------------------------------------
CREATE TABLE silver.quality_entry (
    entry_id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    kind              varchar(20) NOT NULL CHECK (kind IN ('reject','rework','reject_override')),
    work_unit_id      bigint      NOT NULL,
    shift_instance_id bigint      NOT NULL,
    business_date     date,                            -- filled by the trigger
    product_id        bigint      NOT NULL,
    reject_reason_id  bigint,                          -- reject / rework reason; for an override: the NEW reason
    entered_qty       numeric(15,3) NOT NULL CHECK (entered_qty > 0),
    entered_uom_id    bigint      NOT NULL,
    override_tag_id   bigint,                          -- reject_override only: the sensor reject node (qty in its unit)
    reason            text        NOT NULL CHECK (btrim(reason) <> ''),
    created_by        text        NOT NULL,
    created_by_name   varchar(255),
    created_at        timestamptz NOT NULL DEFAULT now(),
    voided_at         timestamptz,
    voided_by         text,
    void_reason       text,
    CHECK ((kind = 'reject_override') = (override_tag_id IS NOT NULL)),
    CHECK (kind = 'rework' OR reject_reason_id IS NOT NULL)
);
CREATE INDEX ON silver.quality_entry (shift_instance_id, work_unit_id) WHERE voided_at IS NULL;

CREATE FUNCTION silver.trg_quality_entry_before() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  PERFORM silver.fn_assert_edit_window(TG_ARGV[0], NEW.shift_instance_id, NEW.work_unit_id);
  SELECT business_date INTO NEW.business_date FROM silver.shift_instance WHERE shift_instance_id = NEW.shift_instance_id;
  IF NEW.kind = 'reject_override' AND NOT EXISTS (
       SELECT 1 FROM silver.asset_tags t WHERE t.tag_id = NEW.override_tag_id
          AND t.tag_role = 'reject' AND t.uom_id = NEW.entered_uom_id) THEN
    RAISE EXCEPTION 'override_tag_id % must be a reject node whose unit is the entered unit', NEW.override_tag_id;
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER quality_entry_before BEFORE INSERT ON silver.quality_entry
  FOR EACH ROW EXECUTE FUNCTION silver.trg_quality_entry_before('silver');
CREATE TRIGGER quality_entry_append_only BEFORE UPDATE OR DELETE ON silver.quality_entry
  FOR EACH ROW EXECUTE FUNCTION silver.trg_append_only();
CREATE TRIGGER quality_entry_audit AFTER INSERT OR UPDATE ON silver.quality_entry
  FOR EACH ROW EXECUTE FUNCTION silver.trg_edit_audit('MON', 'entry_id');

-- Common trigger: fully immutable (no UPDATE, no DELETE) — for pure event trails.
CREATE FUNCTION silver.trg_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION '%.% is an immutable trail: no UPDATE or DELETE', TG_TABLE_SCHEMA, TG_TABLE_NAME;
END $$;
