"""Generate master-data DDL (schema silver) from the FigJam ERD export."""
import json, re, sys

ERD = __import__("pathlib").Path(__file__).resolve().parents[1] / "erd" / "erd_spec_2026-10-01.json"
d = json.load(open(ERD))
SKIP = {"kpi_result"}   # decided 2026-10-02: gold wide tables replace KPI_RESULT
d["tables"] = [t for t in d["tables"] if t["name"] not in SKIP]
d["relationships"] = [r for r in d["relationships"] if r["child"] not in SKIP and r["parent"] not in SKIP]
tables = {t["name"]: t for t in d["tables"]}

TYPES = {
    "id": "bigint", "string": "text", "date": "date", "enum": "text", "numeric": "numeric",
    "int": "integer", "timestamp": "timestamptz", "timestamptz": "timestamptz", "datetime": "timestamptz",
    "bool": "boolean", "key-value": "jsonb", "list": "jsonb", "time": "time", "ref": "jsonb",
}
# Tables without a PK in the ERD get the surrogate key the PRD names (PRD-003 20-cross-cutting §7.2)
SURROGATE = {
    "asset_component_link": "asset_component_link_id", "kpi_result": "kpi_result_id",
    "asset_placement": "asset_placement_id", "downtime_reason_asset": "downtime_reason_asset_id",
    "reject_reason_asset": "reject_reason_asset_id",
}
RENAME = {("asset_state_log", "(row id — name TBD)"): "asset_state_log_id"}
IDENT = re.compile(r"^[a-z][a-z0-9_]*$")


def enum_values(notes):
    """Pick a comma list of identifiers out of a note like 'nullable — percent, absolute'."""
    for seg in notes.split("—"):
        parts = [p.strip() for p in seg.split(",")]
        if len(parts) >= 2 and all(IDENT.match(p) for p in parts):
            return parts
    return None


def pk_of(t):
    for c in t["columns"]:
        if c["notes"].startswith("PK"):
            return RENAME.get((t["name"], c["name"]), c["name"])
    return SURROGATE[t["name"]]


out = []
domains = ["FOUNDATION", "MAINTENANCE", "PRODUCTION"]
for dom in domains:
    out.append(f"\n-- ===================== {dom} =====================")
    for t in [t for t in d["tables"] if t["domain"] == dom]:
        name, pk = t["name"], pk_of(t)
        lines = []
        if name in SURROGATE:
            lines.append((f"    {pk} bigint GENERATED BY DEFAULT AS IDENTITY", "surrogate PK (PRD keys rule)"))
        for c in t["columns"]:
            col = RENAME.get((name, c["name"]), c["name"])
            typ = TYPES[c["type"]]
            n = c["notes"]
            parts = [f"    {col} {typ}"]
            if n.startswith("PK"):
                if typ == "bigint":
                    parts = [f"    {col} bigint GENERATED BY DEFAULT AS IDENTITY"]
            elif ("FK" in n and "nullable" not in n and "conditional" not in n and "?" not in n) or col == "valid_from":
                parts.append("NOT NULL")
            if "(1:1)" in n:
                parts.append("UNIQUE")
            ev = enum_values(n) if c["type"] == "enum" else None
            if ev:
                parts.append("CHECK (" + col + " IN (" + ", ".join(f"'{v}'" for v in ev) + "))")
            lines.append((" ".join(parts), f"{c['type']}{' · ' + n if n else ''}"))
        lines.append((f"    PRIMARY KEY ({pk})", None))
        if any(c["name"] == "valid_to" for c in t["columns"]):
            lines.append(("    CHECK (valid_to IS NULL OR valid_to >= valid_from)", None))
        out.append(f"\n-- {name} · {t['module']}")
        out.append(f"CREATE TABLE silver.{name} (")
        body = []
        for i, (sql, cm) in enumerate(lines):
            sep = "," if i < len(lines) - 1 else ""
            body.append(f"{sql}{sep}" + (f"   -- {cm}" if cm else ""))
        out.append("\n".join(body))
        out.append(");")

out.append("\n-- ===================== FOREIGN KEYS (102, from the ERD) =====================")
for r in d["relationships"]:
    p = tables[r["parent"]]
    out.append(f"ALTER TABLE silver.{r['child']} ADD FOREIGN KEY ({r['fk']}) "
               f"REFERENCES silver.{r['parent']} ({pk_of(p)});")
out.append("\n-- FK indexes")
seen = set()
for r in d["relationships"]:
    k = (r["child"], r["fk"])
    if k not in seen:
        seen.add(k)
        out.append(f"CREATE INDEX ON silver.{r['child']} ({r['fk']});")

open(sys.argv[1], "w").write("\n".join(out) + "\n")
print(len(d["tables"]), "tables,", len(d["relationships"]), "FKs,", len(seen), "indexes")
